install: sudo apt-get install g++ build-essential autoconf libtool libssl-dev scons libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev
before_script: autoreconf -vfi
script: ./configure --prefix=/usr && make 

