language: cpp
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
install: 
    - sudo apt-get install -qq gcc-4.8 g++-4.8 build-essential autoconf libtool inotify-tools unzip wget git scons
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++
    - wget http://dfz.pt/public/zapata-dependencies_precise.deb
    - sudo dpkg -i zapata-dependencies_precise.deb
    - git clone --branch=26compat git://github.com/mongodb/mongo-cxx-driver.git
    - cd mongo-cxx-driver
    - sudo scons --prefix=/usr --sharedclient --use-system-boost --full install-mongoclient
before_script: 
    - autoreconf -vfi
script: 
    - ./configure --prefix=/usr && make 

