language: cpp
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
install: 
    - sudo apt-get install -qq gcc-4.8 g++-4.8
    - export CXX="g++-4.8"
    - wget http://dfz.pt/public/zapata-dependencies-0.1-1.deb
    - sudo dpkg -i zapata-dependencies-0.1-1.deb
    - git clone --branch=26compat git://github.com/mongodb/mongo-cxx-driver.git
    - cd mongo-cxx-driver
    - sudo scons --prefix=/usr --sharedclient --use-system-boost --full install-mongoclient
    - cd ..
before_script: 
    - autoreconf -vfi
script: 
    - ./configure --prefix=/usr && make 
